In [1]:
numbers = [10, 20, 30, 40, 50]
print("Original List:", numbers)

# append
numbers.append(60)
print("After append:", numbers)

# extend
numbers.extend([70, 80])
print("After extend:", numbers)

# insert
numbers.insert(2, 25)
print("After insert:", numbers)

# remove
numbers.remove(40)
print("After remove:", numbers)

# pop
numbers.pop()
print("After pop:", numbers)

# index
print("Index of 30:", numbers.index(30))

# count
print("Count of 20:", numbers.count(20))

# sort
numbers.sort()
print("After sort:", numbers)

# reverse
numbers.reverse()
print("After reverse:", numbers)

# clear
numbers.clear()
print("After clear:", numbers)

Original List: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 25, 30, 50, 60, 70, 80]
After pop: [10, 20, 25, 30, 50, 60, 70]
Index of 30: 3
Count of 20: 1
After sort: [10, 20, 25, 30, 50, 60, 70]
After reverse: [70, 60, 50, 30, 25, 20, 10]
After clear: []


In [3]:
students = ("Alice", "Bob", "Charlie")
print("Original Tuple:", students)

# Trying to change second name
students[1] = "David"

#TypeError: 'tuple' object does not support item assignment

Original Tuple: ('Alice', 'Bob', 'Charlie')


TypeError: 'tuple' object does not support item assignment

In [5]:
my_set = {1, 2, 3, 4, 4, 5, 5, 6}
print("Set:", my_set)
#Set automatically removes duplicate values

Set: {1, 2, 3, 4, 5, 6}


In [7]:
person = {
    "name": "John",
    "age": 25,
    "city": "Mumbai"
}

# Update age
person["age"] = 26

# Add new key
person["email"] = "john@example.com"

print("Updated Dictionary:", person)

Updated Dictionary: {'name': 'John', 'age': 26, 'city': 'Mumbai', 'email': 'john@example.com'}


In [9]:
age = 20

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


In [11]:
marks = 82

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

Grade: B


In [13]:
num = 10

if num > 0:
    print("Number is positive")
    if num % 2 == 0:
        print("Number is also even")
    else:
        print("Number is odd")
elif num == 0:
    print("Number is zero")
else:
    print("Number is negative")

Number is positive
Number is also even


In [15]:
import numpy as np

# Scalar
scalar = np.array(5)
print("Scalar:")
print(scalar)

# 1D Array (1 to 5)
array_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:")
print(array_1d)

# 2D Array (2x3) from 10 to 60 step 10
array_2d = np.arange(10, 70, 10).reshape(2, 3)
print("\n2D Array (2x3):")
print(array_2d)

Scalar:
5

1D Array:
[1 2 3 4 5]

2D Array (2x3):
[[10 20 30]
 [40 50 60]]


In [17]:
import numpy as np

random_array = np.random.randint(0, 101, size=(4, 4))
print("4x4 Random Array:")
print(random_array)

4x4 Random Array:
[[91 99 86 22]
 [85 14 59 85]
 [54 84 81  1]
 [89 34 93 29]]


In [19]:
import numpy as np
import pandas as pd

# Create 3x3 array
array_3x3 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Convert to DataFrame
df = pd.DataFrame(array_3x3, columns=['A', 'B', 'C'])

print("Pandas DataFrame:")
print(df)

Pandas DataFrame:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [21]:
import pandas as pd
import numpy as np

# Create DataFrame with 10 rows
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva",
             "Frank", "Grace", "Helen", "Ivy", "Alice"],
    "Age": [25, 30, 35, 28, 22,
            40, 29, 31, 27, 25],
    "City": ["Mumbai", "Delhi", "Chennai", "Kolkata", "Pune",
             "Delhi", "Mumbai", "Chennai", "Pune", "Mumbai"],
    "Salary": [50000, 60000, np.nan, 55000, 48000,
               70000, 52000, np.nan, 51000, 50000]
}

df = pd.DataFrame(data)

print("Original DataFrame:\n")
print(df)

# -----------------------------
# 1️⃣ Info
print("\nDataFrame Info:\n")
print(df.info())

# -----------------------------
# 2️⃣ Describe
print("\nDataFrame Description:\n")
print(df.describe())

# -----------------------------
# 3️⃣ Select 'Name' and 'City'
print("\nSelected Columns (Name & City):\n")
print(df[["Name", "City"]])

# -----------------------------
# 4️⃣ Drop 'City' column
df = df.drop("City", axis=1)
print("\nAfter Dropping 'City' Column:\n")
print(df)

# -----------------------------
# 5️⃣ Fill missing Salary with mean
mean_salary = df["Salary"].mean()
df["Salary"] = df["Salary"].fillna(mean_salary)

print("\nAfter Filling Missing Salary with Mean:\n")
print(df)

# -----------------------------
# 6️⃣ Remove duplicate rows
df = df.drop_duplicates()

print("\nAfter Removing Duplicates:\n")
print(df)

Original DataFrame:

      Name  Age     City   Salary
0    Alice   25   Mumbai  50000.0
1      Bob   30    Delhi  60000.0
2  Charlie   35  Chennai      NaN
3    David   28  Kolkata  55000.0
4      Eva   22     Pune  48000.0
5    Frank   40    Delhi  70000.0
6    Grace   29   Mumbai  52000.0
7    Helen   31  Chennai      NaN
8      Ivy   27     Pune  51000.0
9    Alice   25   Mumbai  50000.0

DataFrame Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

DataFrame Description:

             Age        Salary
count  10.000000      8.000000
mean   29.200000  54500.000000
std     5.245104   7289.914756
min    22.000000  48000.000000
25%    25.50